type: "box"
name: "table"
size: [1.2, 1.2, 0.05]
init_pos: [0.0, 0.0, 1.0]
fixed: True
# handle: None
# color: [1.0, 1.0, 1.0]
#friction: 1.3
#friction: 1.1
#friction: 1.06 #шонч╗Г
#friction: 0
#friction: 1.05
#friction: 2.0
# noise_percentage_friction: 0.3