type: "box"
name: "shelf_stand"
#size: [.2, .2, .3] #初始大小
#size: [.1, .1, .3] #改小一版
#size: [.07, .07, .3] #改小二版
size: [.05, .05, .3] #改小三版
#init_pos: [0.4, 0.0, 1.175] #初始位置
init_pos: [0.25, 0.0, 1.175]
fixed: True